### ISSUE TITLE
Test against pre-release versions of dependencies

### ISSUE THREAD

**Issue by ivirshup** [owkin/PyDESeq2#170]
Hey! Really like this project, very happy to see DE being brought to python!

I'm wondering if you could add a CI job testing against release candidates of your dependencies. Here's and example of what that looks like over in the [scverse cookiecutter template](https://github.com/scverse/cookiecutter-scverse):

<details>
<summary> Example </summary>

[link](https://github.com/scverse/cookiecutter-scverse/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/test.yaml#L28-L30)

```yaml
jobs:
  test:
    ...
    strategy:
      matrix:
        include:
          ...
          - os: ubuntu-latest
            python: "3.10"
            pip-flags: "--pre"
    ...

    steps:
      ...
      - name: Install dependencies
        run: |
          pip install ${{ matrix.pip-flags }} ".[dev,test]"
```

</details>

I saw you're subclassing AnnData, which isn't a thing we've thought a lot about people doing, so was a little worried future updates might cause problems for you. It would be really good to know about these things before a real release of AnnData goes out, so that we can figure out what to do then.

I'd be happy to help with this if you'd like.

--------

We are starting to do a little bit of thinking about `AnnData` subclasses. Would you be interested in being a part of those conversations?
